### PR TITLE
Moving ignoring players and groups to database

### PR DESCRIPTION
**Pull request by idoash4**
@Maxopoly Don't merge yet I will squash the commits tomorrow and increase the version number.

### CODE REVIEW

**Comment by idoash4** [comment]
@Maxopoly Nice lol

**Comment by idoash4** [comment]
@ProgrammerDan I need your help with git. I cant resubmit the pull. How do I rebase without deleting all the changes I made?

**Comment by ProgrammerDan** [comment]
Whew. Might need one of us Master-mergers to do the merge locally.

As for your local rebase, just rebase against your local branchpoint (before Max reverted).

**Comment by ProgrammerDan** [comment]
Pro-tip: do everything in a new branch first, just to make sure the effect is as desired.

**Comment by ProgrammerDan** [comment]
Looks like https://github.com/Civcraft/CivChat2/commit/c3e2d92e45f599003336a6649b3955da468efafd is the last commit before revert, so you should be able to rebase for squash using:

git rebase -i c3e2d92

but again, I strongly recommend testing it in a new branch against your fixcode.

so

git checkout -b rebase_test

git rebase -i c3e2d92

if everything looks good, delete that local branch, switch to your main fix branch, do it again. Or if your gitfu is strong, you can just use the rebase_test branch and overwrite the tracking branch ... up to you, should be same outcome.

**Pull request merged**
