### PR TITLE
Make op /say command more obvious

### PR DESCRIPTION
**Pull request by jjj5311**
Tested this locally and it appears to work as intended, this overrides say for console command and op players and uses a configurable chat color to broadcast the message serverwide

Should fix issue #18

### CODE REVIEW

**Comment by ttk2** [comment]
cool, whats the default? 

I will let roruke review this before merging, but I expect to have it in testing very soon.

**Comment by ghost** [comment]
> cool, whats the default? 

Default is sad looking white text. /say needs to be intimidating. 

https://github.com/Civcraft/CivChat2/issues/18

@rourke750

**Comment by jjj5311** [comment]
In the config I made it light purple... Might be better as like orange or
something that isn't used for anything else

**Comment by rourke750** [comment]
@drjawa Looks good.
@jjj5311 Mind squashing those commits.

**Comment by jjj5311** [comment]
Ugh knew you were gonna say something about it,

I'll do it in a few minutes

**Comment by jjj5311** [comment]
new pull with things squashed

**Comment by rourke750** [comment]
You don't need to close pull.

**Comment by jjj5311** [comment]
I will re-open it if i can figure this out lol

**Comment by ghost** [comment]
Any change you make in your repo will automagically be reflected in
your pull request

**Comment by jjj5311** [comment]
i know but since i pushed those commits to git already they are stuck there

**Comment by jjj5311** [comment]
@rourke750 not sure what happened one of these commits is not in my local repo? 

Unless you know some magic for doing that this is what you will get lol

**Comment by jjj5311** [comment]
well wtf
ill make anew pull

**Pull request closed without merging**
