### PR TITLE
Improved sharding support, fixing reply and afk commands. Fixing private chat conversations.

### PR DESCRIPTION
**Pull request by idoash4**
@Maxopoly

### CODE REVIEW

**Comment by Maxopoly** [comment]
Gonna add the global /sayall command later and then we can wrap CivChat up. The only really important thing missing then are invitations in NameLayer, we either need to make those global through a broadcast event or keep them in a database. The data base has the advantage that it also persists invites across restarts, so I would prefer that, but you would have to do the SQL part of that, because I dont know anything about it.

**Comment by idoash4** [comment]
We also need to figure out what to do with /ignore. Using files and Mercury means syncing the entire list every few ticks. I think we will have to use a database here as well.

**Comment by Maxopoly** [comment]
Keep a file locally and whenever someone is added on one server, that's broadcasted to all the other so they add it to the file; no syncing aside from that. That's easy to do.

**Comment by idoash4** [comment]
What if one of the server crashes? There is a good reason why we sync the player list every few ticks.

**Comment by ProgrammerDan** [comment]
Black's right on this one. In multiserver environments deltas alone are insufficient, you need to do periodic full-resyncs. 

DB is the only right answer here.

**Comment by erocs** [comment]
The pattern plugins should be using is DB for persistence, and initial
(potentially partial) load from the DB on start into a cache, and periodic
updates from Mercury or refreshes from the DB as time goes on.

**Pull request merged**
