### PR TITLE
Fix for /ignoregroup and new features

### PR DESCRIPTION
**Pull request by suirad**
- Fixed Civcraft/CivChat2/issues/17
- Fixed Civcraft/CivChat2/issues/20
- Added Civcraft/CivChat2/issues/19

### CODE REVIEW

**Comment by ghost** [comment]
Looks fine to me, but pending additional review to avoid another mergecopaylpse.

**Comment by jjj5311** [comment]
@suirad  did you test this? I am worried something more is wrong because ignoring another player does not work either

**Comment by suirad** [comment]
I did test this in my dev enviroment. I can do a quick check of regular ignoring if you'd like.
For this one, it looked to be just a small overlook.

**Comment by suirad** [comment]
I just tested player ignoring, it is working just fine on my servers.(I also tested ignoring on cross server pm's just to be sure, since it uses the same ignore checks as regular pm's)

**Comment by jjj5311** [comment]
Awesome thanks for checking on that, how about chatlogs on your local server? are they working as expected? I haven't had time to setup a test server again yet to check

**Comment by jjj5311** [comment]
@drjawa looks good

**Comment by suirad** [comment]
The chat logs work, a little wonky with new lines(im looking into it atm), but functionally working no problem.

**Comment by suirad** [comment]
Ah it seems my windows doesn't like \n for the line separator. Meh, thats something that could be corrected later.

**Comment by jjj5311** [comment]
Those are the same results i had when testing locally awhile ago... the
main server is having issues with chatlogs but i am guessing it could be
caused by the volume of chat on the main server

**Comment by suirad** [comment]
I suppose if no one makes an issue for it, its nbd.

**Comment by suirad** [comment]
Actually while im looking through the issues, adding this feature: https://github.com/Civcraft/CivChat2/issues/19

**Comment by jjj5311** [comment]
#15 is the chat log issue by erocs

**Comment by suirad** [comment]
Updated commit to address: https://github.com/Civcraft/CivChat2/issues/19

**Comment by suirad** [comment]
Updated top post. All features have been tested by myself and need to be bumped to civtest for confirmation. 
Ready to merge.

**Comment by ttk2** [comment]
looks like no mergebot here, so here goes nothing.

**Comment by ttk2** [comment]
this isn't building.

**Comment by ttk2** [comment]
http://build.civcraft.co/job/CivChat2-master/

think it might be more of a jenkins issue.

**Comment by ghost** [comment]
http://build.civcraft.co/job/CivChat2-master/7/console

[INFO] -------------------------------------------------------------
[ERROR] /var/lib/jenkins/workspace/CivChat2-master/src/vg/civcraft/mc/civchat2/listeners/CivChat2Listener.java:[17,29] error: package vg.civcraft.mc.mercury does not exist
[ERROR] /var/lib/jenkins/workspace/CivChat2-master/src/vg/civcraft/mc/civchat2/command/CivChat2CommandHandler.java:[9,40] error: package vg.civcraft.mc.civmodcore.command does not exist
[ERROR] /var/lib/jenkins/workspace/CivChat2-master/src/vg/civcraft/mc/civchat2/command/CivChat2CommandHandler.java:[21,20] error: cannot find symbol

And more

**Comment by ttk2** [comment]
ah new dependency.

**Pull request merged**
